### PR TITLE
feat: Substrate 3 update attempt 2

### PR DESCRIPTION
**Pull request by ltfschoen**
[x] Compiles successfully after:
```
rm -rf /tmp/polkadot-chains
cargo +nightly-2021-03-10 build --release
```
[x] Check that transfers work (prior to each commit) using Polkadot.js Apps and importing latest custom_types.json file
```
RUST_LOG=debug RUST_BACKTRACE=1  ./target/release/datahighway \
  --base-path /tmp/polkadot-chains/alice \
  --name "Data Highway Development Chain" \
  --dev \
  --telemetry-url "wss://telemetry.polkadot.io/submit/ 0" \
-lruntime=debug
```
[ ] Prior to merging into master, check that it connects as a node to "harbour" chain, i.e.
we should also switched to "christian/harbour" branch, which is currently deployed branch for "harbour" chain, then start the nodes, and it should  produced blocks without stopping, same on our updates and in master branch
We need to run the following and it should work

IMPORTANT: Replace the bootnode address with the one at https://dev.datahighway.com/docs/en/tutorials/tutorials-nodes-validator-setup
```
rm ./node/src/chain-spec-templates/chain_spec_harbour.json &&
mkdir -p ./node/src/chain-spec-templates &&
touch ./node/src/chain-spec-templates/chain_spec_harbour.json &&
./target/release/datahighway build-spec \
  --chain=harbour > ./node/src/chain-spec-templates/chain_spec_harbour.json

rm ./node/src/chain-definition-custom/chain_def_harbour.json &&
mkdir -p ./node/src/chain-definition-custom &&
touch ./node/src/chain-definition-custom/chain_def_harbour.json &&
./target/release/datahighway build-spec \
  --chain ./node/src/chain-spec-templates/chain_spec_harbour.json \
  --raw > ./node/src/chain-definition-custom/chain_def_harbour.json

./target/release/datahighway --validator \
  --unsafe-ws-external \
  --unsafe-rpc-external \
  --rpc-cors=all \
  --base-path /tmp/polkadot-chains/alice \
  --keystore-path "/tmp/polkadot-chains/alice/keys" \
  --chain ./node/src/chain-definition-custom/chain_def_harbour.json \
  --node-key 88dc3417d5058ec4b4503e0c12ea1a0a89be200fe98922423d4334014fa6b0ee \
  --bootnodes /ip4/18.185.37.254/tcp/30333/p2p/12D3KooWFmR35FFHiXcQv8hsFWDq6ofttqBPeMkd4Jt6qRgq3HnT \
  --name MyHarbourNode \
  --port 30333 \
  --ws-port 9944 \
  --rpc-port 9933 \
  --telemetry-url "wss://telemetry.polkadot.io/submit/ 0" \
  --execution=native \
  -lruntime=debug \
  --rpc-methods=Unsafe
```
 
[x] Fix tests, when i run `cargo test -p datahighway-runtime --test cli_integration_tests_mining_tokens` i get error that i haven't mocked frame_system's type `BlockLength` and type `BlockWeights`
[x] Try to get Treasury to work by adding bounties and tips
[x] Try to get ImOnline to work (optional)
[x] Update chain_spec.rs to use the Substrate 3 file structure
[x] Split into two runtimes for testnet and mainnet so we can use different SS58 Address Prefix for each
[x] Check that it finalizes blocks when running local (i.e. run sufficient nodes)

### CODE REVIEW

**Comment by cgroeschel** [comment]
@ltfschoen reg. "we should also switched to "christian/harbour" branch, which is currently deployed branch for "harbour" chain", the harbour network was updated with lastest master yesterday and chain reset. Not sure how that affects this PR...

**Comment by cgroeschel** [comment]
@ltfschoen there are some conflicts and test failing

**Comment by ltfschoen** [comment]
> @ltfschoen reg. "we should also switched to "christian/harbour" branch, which is currently deployed branch for "harbour" chain", the harbour network was updated with lastest master yesterday and chain reset. Not sure how that affects this PR...

i think we just continue merging approved PRs that are related to the standalone chain into the "master" branch, don't you think?

**Comment by ltfschoen** [comment]
> @ltfschoen there are some conflicts and test failing

ok i'll take a look now

**Comment by ltfschoen** [comment]
> @ltfschoen there are some conflicts and test failing

haha, name clashes because they changed `Trait` to `Config` in Substrate 3, and we've got some pallets with `Config` in the name

**Comment by ltfschoen** [comment]
i've tried my best to pass all the tests in the Substrate 3 branch

but can't figure out how to mock PalletInfo, RuntimeBlockWeights, and RuntimeBlockHeights

```
error[E0308]: mismatched types
   --> runtime/tests/cli_integration_tests_mining_tokens.rs:105:47
    |
105 |         pub RuntimeBlockLength: BlockLength = ();
    |                                 -----------   ^^ expected struct `BlockLength`, found `()`
    |                                 |
    |                                 expected `BlockLength` because of return type

warning: 5 warnings emitted

error[E0308]: mismatched types
   --> runtime/tests/cli_integration_tests_mining_tokens.rs:106:49
    |
106 |         pub RuntimeBlockWeights: BlockWeights = ();
    |                                  ------------   ^^ expected struct `BlockWeights`, found `()`
    |                                  |
    |                                  expected `BlockWeights` because of return type

error[E0308]: mismatched types
   --> runtime/tests/cli_integration_tests_mining_tokens.rs:105:47
    |
105 |         pub RuntimeBlockLength: BlockLength = ();
    |                                               ^^ expected struct `BlockLength`, found `()`

error[E0308]: mismatched types
   --> runtime/tests/cli_integration_tests_mining_tokens.rs:106:49
    |
106 |         pub RuntimeBlockWeights: BlockWeights = ();
    |                                                 ^^ expected struct `BlockWeights`, found `()`
warning: trait objects without an explicit `dyn` are deprecated
   --> runtime/tests/cli_integration_tests_roaming.rs:159:27
    |
159 |         type PalletInfo = PalletInfo;
    |                           ^^^^^^^^^^ help: use `dyn`: `dyn PalletInfo`
    |
    = note: `#[warn(bare_trait_objects)]` on by default

error[E0277]: the size for values of type `(dyn PalletInfo + 'static)` cannot be known at compilation time
   --> runtime/tests/cli_integration_tests_mining_hardware.rs:122:27
    |
122 |         type PalletInfo = PalletInfo;
    |                           ^^^^^^^^^^ doesn't have a size known at compile-time
    | 
   ::: /Users/ls2/.cargo/registry/src/github.com-1ecc6299db9ec823/frame-system-3.0.0/src/lib.rs:233:9
    |
233 |         type PalletInfo: PalletInfo;
    |         ---------------------------- required by this bound in `frame_system::Config`
    |
    = help: the trait `Sized` is not implemented for `(dyn PalletInfo + 'static)`

error[E0038]: the trait `PalletInfo` cannot be made into an object
    --> runtime/tests/cli_integration_tests_mining_hardware.rs:122:9
     |
122  |         type PalletInfo = PalletInfo;
     |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `PalletInfo` cannot be made into an object
     | 
    ::: /Users/ls2/.cargo/registry/src/github.com-1ecc6299db9ec823/frame-support-3.0.0/src/traits.rs:1457:8
     |
1457 |     fn index<P: 'static>() -> Option<usize>;
     |        ----- the trait cannot be made into an object because associated function `index` has no `self` parameter
1458 |     /// Convert the given pallet `P` into its name as configured in the runtime.
1459 |     fn name<P: 'static>() -> Option<&'static str>;
     |        ---- the trait cannot be made into an object because associated function `name` has no `self` parameter
```

but otherwise i've renamed everything from Config to Setting to avoid the name conflicts due to Substrate 3 using Config instead of Trait

**Comment by festelo** [comment]
tests are fixed

**Comment by cgroeschel** [comment]
@ltfschoen @festelo there are some conflicts

**Comment by cgroeschel** [comment]
@ltfschoen lets please bump the version, maybe just match it to substrate, eg. 3.0.1?

**Comment by ltfschoen** [comment]
I've checked that it finalizes blocks when I run
```
cargo build --release

rm ./node/src/chain-spec-templates/chain_spec_local.json &&
mkdir -p ./node/src/chain-spec-templates &&
touch ./node/src/chain-spec-templates/chain_spec_local.json &&
./target/release/datahighway build-spec \
  --chain=local > ./node/src/chain-spec-templates/chain_spec_local.json

rm ./node/src/chain-definition-custom/chain_def_local.json &&
mkdir -p ./node/src/chain-definition-custom &&
touch ./node/src/chain-definition-custom/chain_def_local.json &&
./target/release/datahighway build-spec \
  --chain ./node/src/chain-spec-templates/chain_spec_local.json \
  --raw > ./node/src/chain-definition-custom/chain_def_local.json

rm -rf /tmp/polkadot-chains

SKIP_WASM_BUILD=1 RUST_LOG=runtime=debug \
./target/release/datahighway \
  --unsafe-ws-external \
  --unsafe-rpc-external \
  --rpc-cors=all \
  --base-path /tmp/polkadot-chains/alice \
  --chain local \
  --alice \
  --port 30333 \
  --ws-port 9944 \
  --rpc-port 9933 \
  --node-key 88dc3417d5058ec4b4503e0c12ea1a0a89be200fe98922423d4334014fa6b0ee \
  --telemetry-url 'wss://telemetry.polkadot.io/submit/ 0' \
  --validator \
  --execution=native \
  -lruntime=debug \
  --rpc-methods=Unsafe

SKIP_WASM_BUILD=1 RUST_LOG=runtime=debug \
./target/release/datahighway \
  --unsafe-ws-external \
  --unsafe-rpc-external \
  --rpc-cors=all \
  --base-path /tmp/polkadot-chains/bob \
  --bootnodes /ip4/127.0.0.1/tcp/30333/p2p/12D3KooWKS7jU8ti7S5PDqCNWEj692eUSK3DLssHNwTQsto9ynVo \
  --chain ./node/src/chain-definition-custom/chain_def_local.json \
  --bob \
  --port 30334 \
  --ws-port 9945 \
  --rpc-port 9934 \
  --telemetry-url 'wss://telemetry.polkadot.io/submit/ 0' \
  --validator \
  --execution=native \
  -lruntime=debug \
  --rpc-methods=Unsafe

SKIP_WASM_BUILD=1 RUST_LOG=runtime=debug \
./target/release/datahighway \
  --unsafe-ws-external \
  --unsafe-rpc-external \
  --rpc-cors=all \
  --base-path /tmp/polkadot-chains/charlie \
  --bootnodes /ip4/127.0.0.1/tcp/30333/p2p/12D3KooWKS7jU8ti7S5PDqCNWEj692eUSK3DLssHNwTQsto9ynVo \
  --chain ./node/src/chain-definition-custom/chain_def_local.json \
  --charlie \
  --port 30335 \
  --ws-port 9946 \
  --rpc-port 9935 \
  --telemetry-url 'wss://telemetry.polkadot.io/submit/ 0' \
  --validator \
  --execution=native \
  -lruntime=debug \
  --rpc-methods=Unsafe

SKIP_WASM_BUILD=1 RUST_LOG=runtime=debug \
./target/release/datahighway \
  --unsafe-ws-external \
  --unsafe-rpc-external \
  --rpc-cors=all \
  --base-path /tmp/polkadot-chains/dave \
  --bootnodes /ip4/127.0.0.1/tcp/30333/p2p/12D3KooWKS7jU8ti7S5PDqCNWEj692eUSK3DLssHNwTQsto9ynVo \
  --chain ./node/src/chain-definition-custom/chain_def_local.json \
  --dave \
  --port 30336 \
  --ws-port 9947 \
  --rpc-port 9936 \
  --telemetry-url 'wss://telemetry.polkadot.io/submit/ 0' \
  --validator \
  --execution=native \
  -lruntime=debug \
  --rpc-methods=Unsafe
```

**Review by cgroeschel — APPROVED** [review]
looks good, thx

**Review by festelo — APPROVED** [review]
lgtm

**Review by ltfschoen — COMMENTED** [review]
indentation needs fixing but merging anyway

**Pull request merged**
